# -*- coding: utf-8 -*-
"""
Created on Sun Apr 27 15:57:04 2025

@author: yutah
"""
import numpy as np
from kmer_topology import KmerTopology, KmerHomology

length_seq = 1000
sequence = np.random.choice(['A', 'C', 'G', 'T'], length_seq)
sequence = 'CTAGAAGATCAATTAAACCCATCAACACGAGTGATTCACTATAAAAAAGCCGTGGCGGCCACTTGCCAATACTTGGTAGCAATCTCTAGAAACGTACGTTGAGAGGGGTCAAAAGTCGCTCCGTGTAATGTGATCGCCAGATACCGTAATTCCTCGAGAGACCCGGGAGCGCGAGCATCCAGCCTTGTATCATACTAGCCGCTTAACGCAAATCCTCGGTAACGATTGGCATGTCGTCTTAGATTACTTCACACTGGTTCGATATCTGTATCCACGGCCGACGTAGCACACTGAATAAGGACGGTAATATGCTTTTACTCTACCGTACCTATCGAGAGAGGTCCTATCTTGGTCGGTTATACACCCTCTCACCCATGTTATAAGAGCAGATGAGTCTGCCTCAGTTGCACCGTAAGTTGCGCTAGCCGAATACTAAAGATAATCTCGGTAAAAAGACATCTGCCACGATACCGGGGGTTACAGCGGACCCCATCCATGTCGTTCGCCCCAGGCGATTTGGAATGCTCAATAAGCTGAAATCGTCCTTATCTCCTTTAATTTATGAACGACACGCCGTCTCTACAGCACATATGAACACCTAGTGCCAGGGTTTCTTCAGTAGTCCTGCCCGGCCCTAAAGTGTCATAGGCTCCCTCCCCCACCAAGTCCTTCATTCGGAAAAATAGTGATTATCAGTGGTGTTACACCTGCAAGGTAATCTTGCTGAATTTTCCAAGAGCTAACTTTGATCGTTAGGTCGGTTGCAGAGGGTAATGGCAATCCTAGGTCGCCGTTCGCAGTCGTTCCGATTTCGCTTGCCATGCCGATCATGCCAGTATTCTGCTACGGTAGGCGCCCTGTGCGCCAATATCATCCACGGGGATCTACGAGCGACGGTGACCTAGACTAAAATACTTAGTATTTACATCTTTGCCAATATAGAATGCTGATTCATTCTTGGTGCTGAAGATGTACCACGTAGAGTCGTGTAGGGACTTGG'

step = np.arange(50)
kmers_size = 2
kmers = 'A'


b, e = KmerTopology(sequence, 2, 4, 50)
bb = KmerHomology(sequence, 2, 4, 50)